artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data/genres_original

data_transformation:
  file_path_30: artifacts/data/features_30_sec.csv
  file_path_3: artifacts/data/features_3_sec.csv
  transformed_data: artifacts/transformed_data

model_trainer:
  train_input_data: artifacts/transformed_data/train.csv
  test_input_data: artifacts/transformed_data/test.csv
  save_model_path: artifacts/models


model_evaluation:
  test_input_data: artifacts/transformed_data/test.csv
  model_path: artifacts/models
  metrics_path: artifacts/performance
  plots_path: artifacts/plots